//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.17 at 10:24:54 PM CET 
//


package pt.vgaspar.chordguess.autogenconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}chords"/>
 *         &lt;element ref="{}screens"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chords",
    "screens"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(required = true)
    protected Chords chords;
    @XmlElement(required = true)
    protected Screens screens;

    /**
     * Gets the value of the chords property.
     * 
     * @return
     *     possible object is
     *     {@link Chords }
     *     
     */
    public Chords getChords() {
        return chords;
    }

    /**
     * Sets the value of the chords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chords }
     *     
     */
    public void setChords(Chords value) {
        this.chords = value;
    }

    /**
     * Gets the value of the screens property.
     * 
     * @return
     *     possible object is
     *     {@link Screens }
     *     
     */
    public Screens getScreens() {
        return screens;
    }

    /**
     * Sets the value of the screens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screens }
     *     
     */
    public void setScreens(Screens value) {
        this.screens = value;
    }

}
