//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.17 at 10:24:54 PM CET 
//


package pt.vgaspar.chordguess.autogenconfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.vgaspar.chordguess.autogenconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.vgaspar.chordguess.autogenconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Chords }
     * 
     */
    public Chords createChords() {
        return new Chords();
    }

    /**
     * Create an instance of {@link Chord }
     * 
     */
    public Chord createChord() {
        return new Chord();
    }

    /**
     * Create an instance of {@link Use }
     * 
     */
    public Use createUse() {
        return new Use();
    }

    /**
     * Create an instance of {@link Screens }
     * 
     */
    public Screens createScreens() {
        return new Screens();
    }

    /**
     * Create an instance of {@link ChordGuess }
     * 
     */
    public ChordGuess createChordGuess() {
        return new ChordGuess();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

}
