//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.17 at 10:24:54 PM CET 
//


package pt.vgaspar.chordguess.autogenconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}chordGuess"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chordGuess"
})
@XmlRootElement(name = "screens")
public class Screens {

    @XmlElement(required = true)
    protected ChordGuess chordGuess;

    /**
     * Gets the value of the chordGuess property.
     * 
     * @return
     *     possible object is
     *     {@link ChordGuess }
     *     
     */
    public ChordGuess getChordGuess() {
        return chordGuess;
    }

    /**
     * Sets the value of the chordGuess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChordGuess }
     *     
     */
    public void setChordGuess(ChordGuess value) {
        this.chordGuess = value;
    }

}
